// 英語の訳語（正規化キー → gloss）。日本語の意味と同じ粒度の短い訳。
module.exports = {
'август':'August','апрель':'April','арбуз':'watermelon','баба-яга':'Baba Yaga (witch of Russian tales)',
'бабушка':'grandmother','балетки':'ballet flats','бант':'bow (ribbon)','бантик':'little bow',
'бежать':'to run (one way)','без':'without','бейсболка':'baseball cap','беловатый':'whitish',
'белый':'white','берет':'beret','бесцветный':'colourless','бледно-':'pale- (before a colour)',
'блузка':'blouse','бог':'god','больше':'bigger; more','большой':'big','борода':'beard',
'ботинки':'ankle boots','бояться':'to be afraid of (+gen.)','брат':'brother','брови':'eyebrows',
'брюки':'trousers','букет':'bouquet','быстрый':'fast','быть':'to be','в-':'(prefix) into',
'валенки':'felt boots (valenki)','варежки':'mittens','верблюд':'camel','весело':'(it is) fun',
'весна':'spring','веснушки':'freckles','видеть':'to see','висеть':'to be hanging','вкусный':'tasty',
'внимательный':'attentive','вода':'water','волосы':'hair','воротник':'collar','воскресенье':'Sunday',
'время':'time','встречаться':'to meet (each other)','вторник':'Tuesday','вы-':'(prefix) out of',
'высокий':'tall; high','вязаная шапка':'knitted hat','глаза':'eyes','говорить':'to speak',
'голубой':'light blue','горох':'peas','грибы':'mushrooms','грустно':'(it is) sad','губы':'lips',
'гулять':'to stroll','дать':'to give','дача':'dacha (country house)','дед':'grandfather (old man)',
'декабрь':'December','делать':'to do; to make','деньги':'money (pl. only)','дерево':'tree',
'дешёвый':'cheap','джинсы':'jeans','длинный':'long','для':'for','до свидания':'goodbye',
'до-':'(prefix) as far as','добрый':'kind','довольно':'rather','дождь':'rain','доктор':'doctor',
'должен':'must; obliged to','дом':'house','дорогой':'expensive; dear','друг':'friend',
'духи':'perfume (pl. only)','единорог':'unicorn','ёж':'hedgehog','ездить':'to go (by vehicle, habitually)',
'ёлка':'fir tree; Christmas tree','есть':'to eat','ехать':'to go (by vehicle, one way)','жадный':'greedy',
'жара':'heat','жарко':'(it is) hot','желтоватый':'yellowish','жёлтый':'yellow','живот':'belly',
'жить':'to live','за-':'(prefix) drop in','заниматься':'to be engaged in (+instr.)','застенчивый':'shy (by nature)',
'звезда':'star','звонить':'to phone (+dat.)','здороваться':'to greet each other','здравствуйте':'hello (polite)',
'зеленоватый':'greenish','зелёный':'green','зеркало':'mirror','зима':'winter','знать':'to know',
'золотой':'golden','иван-дурак':'Ivan the Fool (folk hero)','играть':'to play','идти':'to go (on foot, one way)',
'из':'out of; from','извините':'excuse me','изучать':'to study (a subject)','икра':'caviar','имя':'name',
'интересно':'(it is) interesting','интересный':'interesting','интересоваться':'to be interested in (+instr.)',
'июль':'July','июнь':'June','йога':'yoga','к':'to; towards (+dat.)','канотье':'boater hat','капюшон':'hood',
'каре':'bob (haircut)','карий':'brown (of eyes)','карман':'pocket','картуз':'peaked cap (old style)',
'квадрат':'square','квадратный':'square (adj.)','кеды':'canvas sneakers','кепка':'flat cap','книга':'book',
'коричневый':'brown (of things)','король':'king (Western tales)','короткий':'short','коса':'braid, plait',
'косички':'pigtails','кот':'cat (male)','кофе':'coffee','кошка':'cat (female)',
'кощей бессмертный':'Koschei the Deathless (villain)','красивый':'beautiful','красноватый':'reddish',
'красный':'red','кроссовки':'sneakers','круг':'circle','круглый':'round','кудри':'curls',
'кудряшки':'little curls','кукла':'doll','кулич':'kulich (tall Easter bread)','купить':'to buy',
'курносый':'snub-nosed','куртка':'jacket','лежать':'to be lying','лес':'forest','лететь':'to fly (one way)',
'лето':'summer','лимон':'lemon','лиса':'fox','листопад':'leaf fall','лицо':'face','ложка':'spoon',
'лоферы':'loafers','лучше':'better','любить':'to love','май':'May','маленький':'small','мама':'mum',
'март':'March','мачеха':'stepmother','меньше':'smaller; less','мертвец':'dead person','меховая шапка':'fur hat',
'мимоза':'mimosa','многоцветный':'multicoloured','можно':'one may; it is allowed','молодой':'young',
'моложе':'younger','молоко':'milk','мороженое':'ice cream','мороз':'hard frost','мочь':'to be able',
'мудрый':'wise','мыться':'to wash oneself','мягкий':'soft; gentle','на автобусе':'by bus',
'на высоком каблуке':'high-heeled','на машине':'by car','на метро':'by metro','на плоской подошве':'flat-soled',
'на поезде':'by train','надёжный':'reliable','надеть':'to put on','надеяться':'to hope','надо':'one must',
'народ':'people, folk','не стесняйтесь!':'don\'t be shy!','нельзя':'one must not','немного':'a little',
'непрозрачный':'opaque','низкий':'low; short','новый':'new','нос':'nose','носить':'to wear (habitually)',
'носки':'socks','носорог':'rhinoceros','ноябрь':'November','нравиться':'to be pleasing (+dat.)',
'нужно':'one needs','о':'about','обниматься':'to hug each other','обо-':'(prefix) around','обувь':'footwear',
'обуться':'to put shoes on','овал':'oval','овальный':'oval (adj.)','одеваться':'to get dressed',
'одноцветный':'plain, one-colour','октябрь':'October','оранжевый':'orange','орех':'nut, walnut',
'орлиный':'aquiline (of a nose)','осень':'autumn','отзывчивый':'sympathetic','ото-':'(prefix) a bit away',
'очень':'very','очки':'glasses (pl. only)','пальто':'coat','панама':'sun hat','пасха':'paskha (Easter dessert)',
'пере-':'(prefix) across','переодеться':'to change clothes','перчатки':'gloves','пёстрый':'motley, gaudy',
'пешком':'on foot','писать':'to write','пить':'to drink','плавать':'to swim (around)','платье':'dress',
'плохой':'bad','по':'along (+dat.)','по-':'(prefix) set off','повесить':'to hang up','подо-':'(prefix) approach',
'подсолнух':'sunflower','подстричься':'to get a haircut','пожалуйста':'please; you\'re welcome',
'положить':'to lay down','помочь':'to help (+dat.)','понедельник':'Monday','попугай':'parrot',
'поставить':'to stand (sth) up','прекрасный':'wonderful, most beautiful','при-':'(prefix) arrival',
'привет':'hi','принц':'prince (Western tales)','про-':'(prefix) past','прозрачный':'transparent',
'прямой':'straight','прямоугольник':'rectangle','пуговица':'button','пустыня':'desert','пучок':'hair bun',
'пятница':'Friday','работа':'work','работать':'to work','раздеться':'to take off (coat etc.)',
'разноцветный':'multicoloured','разуться':'to take shoes off','резиновые сапоги':'rubber boots',
'ресницы':'eyelashes','решительный':'decisive','розовый':'pink','ромашка':'camomile','рот':'mouth',
'рубашка':'shirt','рукав':'sleeve','ручка':'pen','рыжий':'ginger, red (of fur/hair)','с':'with (+instr.)',
'с днём рождения!':'happy birthday!','с новым годом!':'happy new year!','сапоги':'(tall) boots',
'сахар':'sugar','светло-':'light- (before a colour)','свитер':'sweater','сентябрь':'September',
'серый':'grey','серьёзный':'serious','сесть':'to sit down','сидеть':'to be sitting','синеватый':'bluish',
'синий':'(dark) blue','сказать':'to say','скучно':'(it is) boring','сланцы':'flip-flops','след':'footprint',
'слишком':'too (much)','слышать':'to hear','смеяться':'to laugh','смотреть':'to look, to watch','снег':'snow',
'снеговик':'snowman','снимать':'to take off (impf.)','снять':'to take off (pf.)','солнце':'sun',
'соломенная шляпа':'straw hat','спасибо':'thank you','спать':'to sleep','спокойный':'calm','среда':'Wednesday',
'ссориться':'to quarrel','стараться':'to try hard','старше':'older','старый':'old',
'стеснительный':'bashful','стесняться':'to feel shy','стол':'table','стоять':'to be standing',
'странный':'strange','строгий':'strict','студент':'student','суббота':'Saturday','сумка':'bag',
'съёмка':'filming, shoot','сыр':'cheese','тапочки':'slippers','тёмно-':'dark- (before a colour)',
'тепло':'(it is) warm','толстовка':'hoodie, sweatshirt','тост':'toast (drinking)','треугольник':'triangle',
'треугольный':'triangular','труп':'corpse','туфли':'(dress) shoes','тюлень':'seal','тюльпан':'tulip',
'у':'at, by (+gen.)','у-':'(prefix) away','угги':'ugg boots','улыбаться':'to smile','умный':'clever',
'умываться':'to wash one\'s face','университет':'university','упрямый':'stubborn','урожай':'harvest',
'усы':'moustache','утка':'duck','учитель':'teacher','учить':'to memorise; to teach',
'учиться':'to study (at school)','ушанка':'ushanka (ear-flap hat)','уши':'ears','февраль':'February',
'фиолетовый':'violet, purple','флаг':'flag','фуражка':'service cap','футболка':'T-shirt',
'хвостик':'ponytail','хитрый':'cunning','хлеб':'bread','ходить':'to go (on foot, habitually)',
'холодно':'(it is) cold','хороший':'good','хотеть':'to want','хуже':'worse','царевич':'tsarevich (prince)',
'царь':'tsar','цветной':'colour (adj.), in colour','цветок':'flower','цирк':'circus','чай':'tea',
'часы':'clock, watch (pl. only)','чёлка':'fringe, bangs','череп':'skull','чёрный':'black','чёрт':'devil',
'честный':'honest','четверг':'Thursday','читать':'to read','шапка':'hat (warm, brimless)','шарф':'scarf',
'шишка':'pine cone','школа':'school','шлёпанцы':'slides, sandals','шляпа':'(brimmed) hat','щедрый':'generous',
'щёки':'cheeks','щелкунчик':'nutcracker','эхо':'echo','юбка':'skirt','юла':'spinning top','яблоко':'apple',
'январь':'January','ярко-':'bright- (before a colour)',
};
